password = []
size = [
    319,
    32,
    1922,
    1408,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'original'
scroll_style = 'scrollauto'
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'map'
view_only = false
sync-init-clipboard = false

[options]
collapse_toolbar = ''
custom-fps = '30'
codec-preference = 'auto'
i444 = ''
swap-left-right-mouse = ''
touch-mode = ''
alias = 'Dell 7070'
zoom-cursor = ''

[ui_flutter]

[info]
username = 'srackham'
hostname = 'optiplex-7070'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []
