return {
  -- 'saghen/blink.cmp',
  -- dependencies = { 'rafamadriz/friendly-snippets' },
  --
  -- -- use a release tag to download pre-built binaries
  -- version = '1.*',
  --
  -- -- See https://cmp.saghen.dev/installation.html for options
  -- opts = {
  --   keymap = {
  --     preset = 'default',
  --     ["<C-Space>"] = { "select_and_accept" },
  --   },
  --
  --   appearance = {
  --     nerd_font_variant = 'mono'
  --   },
  --
  --   completion = { documentation = { auto_show = true } },
  --
  --   sources = {
  --     default = { 'lsp', 'path', 'snippets', 'buffer' },
  --   },
  --
  --   fuzzy = { implementation = 'prefer_rust_with_warning' }
  -- },
  -- opts_extend = { 'sources.default' }
}
