return {
  'srackham/digraph-picker.nvim',
  enabled = true,
  dependencies = {
    'nvim-telescope/telescope.nvim',
  },
  -- version = '*', -- Install latest tagged version
  config = function()
    local picker = require('digraph-picker')
    picker.setup({
      digraphs = {
        { digraph = 'ae', symbol = '≈', name = 'Approximately equal' },
        { digraph = 'ck', symbol = '✓', name = 'Check mark (tick)' },
        { digraph = 'cl', symbol = '☁', name = 'Cloud' },
        { digraph = 'co', symbol = '©', name = 'Copyright' },
        { digraph = 'da', symbol = '†', name = 'Dagger' },
        { digraph = 'dd', symbol = '‡', name = 'Double dagger' },
        { digraph = 'dg', symbol = '°', name = 'Degree' },
        { digraph = 'el', symbol = '…', name = 'Ellipsis' },
        { digraph = 'em', symbol = '—', name = 'Em dash' },
        { digraph = 'fl', symbol = '⚑', name = 'Flag' },
        { digraph = 'fr', symbol = '☹', name = 'Frowning face' },
        { digraph = 'gc', symbol = '✅', name = 'Green heavy check mark (tick)' },
        { digraph = 'ge', symbol = '≥', name = 'Greater than or equal' },
        { digraph = 'hc', symbol = '✔', name = 'Heavy check mark (tick)' },
        { digraph = 'ht', symbol = '♥', name = 'Heart' },
        { digraph = 'hx', symbol = '✘', name = 'Heavy cross mark' },
        { digraph = 'in', symbol = '∞', name = 'Infinity' },
        { digraph = 'le', symbol = '≤', name = 'Less than or equal' },
        { digraph = 'lq', symbol = '“', name = 'Left double quote' },
        { digraph = 'mn', symbol = '☽', name = 'Moon' },
        { digraph = 'ne', symbol = '≠', name = 'Not equal' },
        { digraph = 'pi', symbol = 'π', name = 'Pi' },
        { digraph = 'pp', symbol = '¶', name = 'Pilcrow (paragraph sign)' },
        { digraph = 'rg', symbol = '®', name = 'Registered' },
        { digraph = 'rq', symbol = '”', name = 'Right double quote' },
        { digraph = 'rx', symbol = '❌', name = 'Red heavy cross mark' },
        { digraph = 'sc', symbol = '✂', name = 'Scissors' },
        { digraph = 'se', symbol = '§', name = 'Section sign' },
        { digraph = 'sm', symbol = '☺', name = 'Smiling face' },
        { digraph = 'su', symbol = '☀', name = 'Sun' },
        { digraph = 'tm', symbol = '™', name = 'Trademark' },
        { digraph = 'um', symbol = '☂', name = 'Umbrella' },
        { digraph = 've', symbol = '⋮', name = 'Vertical ellipsis' },
        { digraph = 'wr', symbol = '✎', name = 'Pencil' },
        { digraph = 'xj', symbol = '☩', name = 'Jerusalem Cross' },
        { digraph = 'xl', symbol = '✝', name = 'Latin Cross' },
        { digraph = 'xm', symbol = '✠', name = 'Maltese Cross' },
        { digraph = 'xo', symbol = '☦', name = 'Orthodox Cross' },
        { digraph = 'xr', symbol = '☧', name = 'Chi Rho' },
        { digraph = 'xx', symbol = '✗', name = 'Cross mark' },
        { digraph = 'zw', symbol = '\u{200B}', name = 'Zero Width Space' },
        -- Nerd Font characters (Nerd Fonts must be installed)
        { digraph = 'rk', symbol = '', name = 'Rocket' },
        { digraph = 'im', symbol = '', name = 'Image' },
        { digraph = 'do', symbol = '󰈙', name = 'Document' },
        { digraph = 'gr', symbol = '', name = 'Gears' },
      },
    })
    vim.keymap.set({ 'i', 'n' }, '<C-k><C-k>', picker.insert_digraph,
      { noremap = true, silent = true, desc = "Digraph picker" })
  end,
}
