return {
  -- "srackham/digraph-picker.nvim",
  dir = "/home/srackham/projects/digraph-picker.nvim",
  enabled = true,
  dependencies = {
    "nvim-telescope/telescope.nvim",
  },
  -- version = '*', -- Install latest tagged version
  config = function()
    local picker = require "digraph-picker"
    picker.setup {
      digraphs = {
        -- Contains some Nerd Font characters (Nerd Fonts must be installed)
        { digraph = "ae", symbol = "≈", name = "Approximately equal" },
        { digraph = "ck", symbol = "✓", name = "Check mark (tick)" },
        { digraph = "cl", symbol = "☁", name = "Cloud" },
        { digraph = "co", symbol = "©", name = "Copyright" },
        { digraph = "da", symbol = "↓", name = "Down arrow" },
        { digraph = "dd", symbol = "‡", name = "Double dagger" },
        { digraph = "dg", symbol = "°", name = "Degree" },
        { digraph = "do", symbol = "󰈙", name = "Document" },
        { digraph = "el", symbol = "…", name = "Ellipsis" },
        { digraph = "em", symbol = "—", name = "Em dash" },
        { digraph = "fl", symbol = "⚑", name = "Flag" },
        { digraph = "fr", symbol = "☹", name = "Frowning face" },
        { digraph = "gc", symbol = "✅", name = "Green heavy check mark (tick)" },
        { digraph = "ge", symbol = "≥", name = "Greater than or equal" },
        { digraph = "gr", symbol = "", name = "Gears" },
        { digraph = "hc", symbol = "✔", name = "Heavy check mark (tick)" },
        { digraph = "ht", symbol = "♥", name = "Heart" },
        { digraph = "hx", symbol = "✘", name = "Heavy cross mark" },
        { digraph = "id", symbol = "≡", name = "Identical to" },
        { digraph = "im", symbol = "", name = "Image" },
        { digraph = "in", symbol = "∞", name = "Infinity" },
        { digraph = "la", symbol = "←", name = "Left arrow" },
        { digraph = "le", symbol = "≤", name = "Less than or equal" },
        { digraph = "lq", symbol = "“", name = "Left double quote" },
        { digraph = "mf", symbol = "♭", name = "Music flat sign" },
        { digraph = "ms", symbol = "♯", name = "Music sharp sign" },
        { digraph = "mn", symbol = "☽", name = "Moon" },
        { digraph = "ne", symbol = "≠", name = "Not equal" },
        { digraph = "ob", symbol = "␣", name = "Open box" },
        { digraph = "pi", symbol = "π", name = "Pi" },
        { digraph = "pp", symbol = "¶", name = "Pilcrow (paragraph sign)" },
        { digraph = "pr", symbol = "🙏", name = "Praying" },
        { digraph = "ra", symbol = "→", name = "Right arrow" },
        { digraph = "rg", symbol = "®", name = "Registered" },
        { digraph = "rk", symbol = "", name = "Rocket" },
        { digraph = "rq", symbol = "”", name = "Right double quote" },
        { digraph = "rx", symbol = "❌", name = "Red heavy cross mark" },
        { digraph = "sc", symbol = "✂", name = "Scissors" },
        { digraph = "sd", symbol = "†", name = "Dagger" },
        { digraph = "se", symbol = "§", name = "Section sign" },
        { digraph = "sm", symbol = "☺", name = "Smiling face" },
        { digraph = "su", symbol = "☀", name = "Sun" },
        { digraph = "td", symbol = "👎", name = "Thumbs down" },
        { digraph = "tm", symbol = "™", name = "Trademark" },
        { digraph = "tu", symbol = "👍", name = "Thumbs up" },
        { digraph = "ua", symbol = "↑", name = "Up arrow" },
        { digraph = "um", symbol = "☂", name = "Umbrella" },
        { digraph = "ve", symbol = "⋮", name = "Vertical ellipsis" },
        { digraph = "wr", symbol = "✎", name = "Pencil" },
        { digraph = "xj", symbol = "☩", name = "Jerusalem Cross" },
        { digraph = "xl", symbol = "✝", name = "Latin Cross" },
        { digraph = "xm", symbol = "✠", name = "Maltese Cross" },
        { digraph = "xo", symbol = "☦", name = "Orthodox Cross" },
        { digraph = "xr", symbol = "☧", name = "Chi Rho" },
        { digraph = "xx", symbol = "✗", name = "Cross mark" },
        { digraph = "zw", symbol = "\u{200B}", name = "Zero Width Space" },
      },
    }
    vim.keymap.set("i", "<C-k><C-k>", picker.insert_digraph, { noremap = true, silent = true, desc = "Digraph picker" })
  end,
}
