theme = "custom_catppuccin_mocha"

[keys.normal]
A-w = ":toggle-option soft-wrap.enable"
F5 = ":reload-all"
C-c = "yank_main_selection_to_clipboard"
C-v = "paste_clipboard_before"
C-n = "page_down"
C-p = "page_up"

#
# Vi compatibility
#
# I've tried to keep only the most must-have Vi bindings.
# See https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
#

V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
A-c = "copy_selection_on_next_line"  # Add selection on next line (default C mapping)
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
";"= ["collapse_selection", "keep_primary_selection"]

[keys.select]
C-c = "yank_main_selection_to_clipboard"
C-n = "page_down"
C-p = "page_up"

[keys.insert]
C-c = "yank_main_selection_to_clipboard"
C-n = "page_down"
C-p = "page_up"
C-v = "paste_clipboard_before"

# Comma minor mode for miscellaneous commands
[keys.normal.","]
c = [":write", ":buffer-close"]
d = [":insert-output date '+%d-%b-%Y'", "move_char_right"]
q = ":write-quit-all"
w = ":write-all!"

[keys.insert.","]
d = [":insert-output date '+%d-%b-%Y'", "move_char_right"]

# Latin long vowels
[keys.insert."A-l"]
a = [":insert-output echo ā", "move_char_right"]
e = [":insert-output echo ē", "move_char_right"]
i = [":insert-output echo ī", "move_char_right"]
o = [":insert-output echo ō", "move_char_right"]
u = [":insert-output echo ū", "move_char_right"]

# Unicode characters
[keys.insert."A-u"]
d = [":insert-output echo †", "move_char_right"]
m = [":insert-output echo —", "move_char_right"]

[editor]
text-width = 120
cursorline = true
rulers = [120]
color-modes = true
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"]

[editor.statusline]
left = [
    "mode",
    "spinner",
    "file-name",
    "file-type",
    "total-line-numbers",
    "file-encoding",
    "file-modification-indicator",
]
center = []
right = [
    "selections",
    "primary-selection-length",
    "position",
    "position-percentage",
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
    "version-control",
]

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[editor.indent-guides]
render = true
character = "▏"

[editor.smart-tab]
enable = false
