theme = "catppuccin_mocha"

[keys.normal]
C-q = [":write-quit-all"]
C-del = [":write", ":buffer-close"]
F5 = ":reload-all"
A-w = ":toggle-option soft-wrap.enable"

[keys.insert]
# Latin long vowels.
A-a = [":insert-output echo ā", "move_char_right"]
A-e = [":insert-output echo ē", "move_char_right"]
A-i = [":insert-output echo ī", "move_char_right"]
A-o = [":insert-output echo ō", "move_char_right"]
A-u = [":insert-output echo ū", "move_char_right"]

[editor]
text-width = 80
cursorline = true
rulers = [120]
color-modes = true

[editor.auto-save]
focus-lost = true

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"]

[editor.statusline]
left = [
    "mode",
    "spinner",
    "file-name",
    "file-type",
    "total-line-numbers",
    "file-encoding",
    "file-modification-indicator",
]
center = []
right = [
    "selections",
    "primary-selection-length",
    "position",
    "position-percentage",
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
    "version-control",
]

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[editor.indent-guides]
render = true
character = "▏"