theme = "catppuccin_mocha"

[keys.normal]
"'" = "keep_primary_selection"
A-w = ":toggle-option soft-wrap.enable"
C-b = ":buffer-next"
C-A-b = ":buffer-previous"
C-del = [":write", ":buffer-close"]
C-q = [":write-quit-all"]
C-tab = ":buffer-next"
C-S-tab = ":buffer-previous"
F5 = ":reload-all"
C-s = [":write-all!"]
C-d = [":insert-output date '+%d-%b-%Y'", "move_char_right"]

[keys.insert]
C-s = [":write-all!"]
C-d = [":insert-output date '+%d-%b-%Y'", "move_char_right"]

# Comma minor mode for miscellaneous commands
[keys.normal.","]
c = [":write", ":buffer-close"]
q = [":write-quit-all"]
s = [":write-all!"]

# Latin long vowels
[keys.insert."A-l"]
a = [":insert-output echo ā", "move_char_right"]
e = [":insert-output echo ē", "move_char_right"]
i = [":insert-output echo ī", "move_char_right"]
o = [":insert-output echo ō", "move_char_right"]
u = [":insert-output echo ū", "move_char_right"]

# Unicode characters
[keys.insert."A-u"]
d = [":insert-output echo †", "move_char_right"]
m = [":insert-output echo —", "move_char_right"]

[editor]
text-width = 80
cursorline = true
rulers = [120]
color-modes = true

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"]

[editor.statusline]
left = [
    "mode",
    "spinner",
    "file-name",
    "file-type",
    "total-line-numbers",
    "file-encoding",
    "file-modification-indicator",
]
center = []
right = [
    "selections",
    "primary-selection-length",
    "position",
    "position-percentage",
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
    "version-control",
]

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[editor.indent-guides]
render = true
character = "▏"
