theme = "monokai_pro_machine"

[editor]
text-width = 80

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[keys.normal]
C-tab = ":buffer-next"
C-S-tab = ":buffer-previous"
F5 = ":reload-all"
A-w = ":toggle-option soft-wrap.enable"

# Some Vi concessions (see https://github.com/LGUG2Z/helix-vim).
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
H = "goto_window_top"
M = "goto_window_center"
L = "goto_window_bottom"
"%" = "match_brackets"
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
# Make j and k behave as they do Vim when soft-wrap is enabled
j = "move_line_down"
k = "move_line_up"