theme = "custom_catppuccin_mocha"

# I've tried to keep only the most must-have Vim bindings.
# See https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

[keys.normal]
del= "delete_selection"
F5 = [":reload-all", ":config-reload"]
C-c = "yank_main_selection_to_clipboard"
C-v = "paste_clipboard_before"
C-k = ["insert_mode", "kill_to_line_end"]
# Vim bindings
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.select]
del= "delete_selection"
F5 = [":reload-all", ":config-reload"]
C-c = "yank_main_selection_to_clipboard"
C-v = "paste_clipboard_before"
# Vim bindings
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"

[keys.insert]
F5 = [":reload-all", ":config-reload"]
C-c = "yank_main_selection_to_clipboard"
C-v = "paste_clipboard_before"
A-D = [":insert-output date '+%d-%b-%Y'", "move_char_right"]

# Custom minor normal mode
[keys.normal."\\"]
"\\" = "goto_last_accessed_file"
c = [":write!", ":buffer-close"]
f = ":format"
w = ":write-all!"
W = ":toggle-option soft-wrap.enable"

# Latin long vowels
[keys.insert."A-l"]
a = [":insert-output echo ā", "move_char_right"]
e = [":insert-output echo ē", "move_char_right"]
i = [":insert-output echo ī", "move_char_right"]
o = [":insert-output echo ō", "move_char_right"]
u = [":insert-output echo ū", "move_char_right"]

# Custom minor insert mode
[keys.insert."A-\\"]
d = [":insert-output echo †", "move_char_right"]
m = [":insert-output echo —", "move_char_right"]

[editor]
text-width = 120
cursorline = true
rulers = [120]
color-modes = true
auto-pairs = false
auto-format = false

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 500

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"]

[editor.statusline]
left = [
    "mode",
    "spinner",
    "file-name",
    "file-type",
    "total-line-numbers",
    "file-encoding",
    "file-modification-indicator",
]
center = []
right = [
    "selections",
    "primary-selection-length",
    "position",
    "position-percentage",
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
    "version-control",
]

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[editor.indent-guides]
render = true
character = "▏"

[editor.smart-tab]
enable = false
