theme = "dark_plus"

[editor]
text-width = 80
cursorline = true

[editor.auto-save]
focus-lost = true

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"]

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[keys.normal]
C-q = [":write-quit-all"]
C-del = [":write", ":buffer-close"]
C-tab = ":buffer-next"
C-S-tab = ":buffer-previous"
F5 = ":reload-all"
A-w = ":toggle-option soft-wrap.enable"
C-left = "jump_backward"
C-right = "jump_forward"

# Some Vi concessions (see https://github.com/LGUG2Z/helix-vim).
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
H = "goto_window_top"
M = "goto_window_center"
L = "goto_window_bottom"
"%" = "match_brackets"
"*" = [
    "move_char_right",
    "move_prev_word_start",
    "move_next_word_end",
    "search_selection",
    "search_next",
]
"#" = [
    "move_char_right",
    "move_prev_word_start",
    "move_next_word_end",
    "search_selection",
    "search_prev",
]

[keys.insert]
# Latin long vowels.
A-a = [":insert-output echo ā", "move_char_right"]
A-e = [":insert-output echo ē", "move_char_right"]
A-i = [":insert-output echo ī", "move_char_right"]
A-o = [":insert-output echo ō", "move_char_right"]
A-u = [":insert-output echo ū", "move_char_right"]
