onboarding = false

[theme]
name = "terminal"
auto_switch = false

[keys]
# prefix = ["ctrl+a", "ctrl+b", "ctrl+s"]
switch_workspace = ["prefix+shift+1..9", "ctrl+shift+1..9"]
next_workspace = ["ctrl+shift+n"]
previous_workspace = ["ctrl+shift+p"]
switch_tab = ["prefix+1..9", "alt+1..9"]
cycle_pane_next = ["prefix+n", "alt+n"]
cycle_pane_previous = ["prefix+p", "alt+p"]
zoom = ["prefix+z", "alt+z"]

# [[keys.command]]
# key = "ctrl+g"
# type = "popup"
# command = "lazygit"
# description = "run lazygit"
# width = "80%"
# height = "100%"

[ui]
tab_bar_position = "bottom"

[ui.sidebar.spaces]
rows = [["state_icon", "workspace"]]

[ui.sidebar.agents]
rows = [["workspace", "state_icon", "tab"]]
