inherits =  "catppuccin_mocha"

# Override theme settings.
"comment" = { fg = "comment" }
"markup.heading.1" = { fg = "green", modifiers = ["bold"] }
"markup.heading.2" = { fg = "green", modifiers = ["bold"] }
"markup.heading.3" = { fg = "green", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "green", modifiers = ["bold"] }
"markup.heading.6" = { fg = "green", modifiers = ["bold"] }
"markup.bold" = { fg = "flamingo", modifiers = ["bold"] }
"markup.italic" = { fg = "flamingo", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
punctuation = "flamingo"
"ui.statusline" = { fg = "white", bg = "surface1" }
"ui.selection" = { bg = "selection" }
"ui.selection.primary" = { bg = "selection" }
"markup.list" = "flamingo"
"markup.link.text" = { fg = "flamingo" }
"markup.link.url" = { fg = "url", modifiers = ["italic", "underlined"] }

[palette]
# Override existing colors or add new colors.
base = "#1c1c1c"
cursorline = "#3a3a3a"
selection = "#005f87"
url = "#5fafd7"
comment = "#87af5f"
