inherits =  "catppuccin_mocha"

# Override theme settings.
"comment" = { fg = "green" }
"markup.heading.1" = { fg = "green", modifiers = ["bold"] }
"markup.heading.2" = { fg = "green", modifiers = ["bold"] }
"markup.heading.3" = { fg = "green", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "green", modifiers = ["bold"] }
"markup.heading.6" = { fg = "green", modifiers = ["bold"] }
"markup.bold" = { fg = "flamingo", modifiers = ["bold"] }
"markup.italic" = { fg = "flamingo", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
punctuation = "flamingo"
"ui.statusline" = { fg = "white", bg = "surface1" }
"ui.selection" = { bg = "selection" }
"ui.selection.primary" = { bg = "selection" }

[palette]
# Override existing colors or add new colors.
cursorline = "#36374a"
selection = "#193D66"
