[env]
TERM = "xterm-256color" # Nany systems do not have the 'alacritty' terminfo entry

[window.dimensions]
columns = 120
lines = 70

[font]
size = 10
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", action = "CreateNewWindow" }
]

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Underline", blinking = "Always" }
blink_interval = 500
blink_timeout = 0
thickness = 1.0

# From [Alacritty themes collection](https://github.com/alacritty/alacritty-theme)
# name = "Monokai (dark)"
# author = "Chris Kempson"
[colors.primary]
background = "#0f0f17"
foreground = "#f8f8f2"

[colors.cursor]
text = "#272822"
cursor = "#f8f8f2"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
