remote_id = '141702961'
kb_layout_type = ''
size = [
    491,
    269,
    1252,
    960,
]
fav = ['141702961']

[options]
show-sessions-type = 'fav'

[ui_flutter]
wm_Main = '{"width":800.0,"height":600.0,"offsetWidth":880.0,"offsetHeight":436.0,"isMaximized":false,"isFullscreen":false}'
peer-sorting = 'Remote ID'
