remote_id = '86382497'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-right = '1.0'
remote-menubar-drag-left = '0.0'

[ui_flutter]
wm_RemoteDesktop = '{"width":1932.0,"height":1120.0,"offsetWidth":324.0,"offsetHeight":186.0,"isMaximized":false,"isFullscreen":false}'
peer-sorting = 'Remote ID'
